config/routes.rb
Rails.application.routes.draw do
  
  resources :weddings
  resources :comments
  
  root 'weddings#index'

  #devise_for :users
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    if user.admin?
        can :manage, Topic
    else
        can :manage, Topic
    end

    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/comment.rb
class Comment
	include Mongoid::Document
  include Mongoid::Timestamps

  belongs_to :wedding

  field :content, type: String
end

app/models/gift.rb
class Gift
  include Mongoid::Document

  embedded_in :wedding

  field :name, type: String
  field :quantity, type: Integer
end

app/models/user.rb
class User
  include Mongoid::Document
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  ## Database authenticatable
  field :email,              type: String, default: ""
  field :encrypted_password, type: String, default: ""

  ## Recoverable
  field :reset_password_token,   type: String
  field :reset_password_sent_at, type: Time

  ## Rememberable
  field :remember_created_at, type: Time

  ## Trackable
  field :sign_in_count,      type: Integer, default: 0
  field :current_sign_in_at, type: Time
  field :last_sign_in_at,    type: Time
  field :current_sign_in_ip, type: String
  field :last_sign_in_ip,    type: String

  ## Confirmable
  # field :confirmation_token,   type: String
  # field :confirmed_at,         type: Time
  # field :confirmation_sent_at, type: Time
  # field :unconfirmed_email,    type: String # Only if using reconfirmable

  ## Lockable
  # field :failed_attempts, type: Integer, default: 0 # Only if lock strategy is :failed_attempts
  # field :unlock_token,    type: String # Only if unlock strategy is :email or :both
  # field :locked_at,       type: Time
  def admin?
    false
  end
end

app/models/wedding.rb
class Wedding
  include Mongoid::Document
  include Mongoid::Timestamps

  embeds_many :gifts
  has_many :comments

  accepts_nested_attributes_for :gifts , allow_destroy: true

  
  field :title,  type: String
  field :url,    type: String
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
  	@comment = Comment.new(comment_params)
  	if @comment.save!
  	  Wedding.find(@comment.wedding.id).touch
  	end
  end

private

  def comment_params
  	params.require(:comment).permit(:content, :wedding_id)
  end

end

app/controllers/weddings_controller.rb
class WeddingsController < ApplicationController
  before_action :set_wedding , only: [:show, :destroy, :edit, :update]

  def new
  	@wedding = Wedding.new
  end
  
  def create
  	@wedding = Wedding.new(wedding_params)
  	if @wedding.save
       redirect_to edit_wedding_path(@wedding)
    end
  end

  def show
  end

  def index
  	@weddings = Wedding.all
  end

  def destroy
  	@wedding.destroy
  	redirect_to weddings_path
  end
  
  def update
    if @wedding.update(wedding_params)
    	redirect_to edit_wedding_path(@wedding)
    end
  end
private

  def wedding_params
  	params.require(:wedding).permit(:title, gifts_attributes: [:name, :quantity, :id, :_destroy])
  end

  def set_wedding
  	@wedding = Wedding.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/weddings_helper.rb
module WeddingsHelper
	def link_to_add_fields(name, f, association)
		new_object = f.object.class.reflect_on_association(association).klass.new
		fields = f.fields_for(association, new_object, :child_index => "new_#{association}") do |builder|
			render(association.to_s.singularize, :gift_fields => builder)
		end

    link_to name, '#', class: 'col-sm-2 control-label', onclick: "add_fields(this, \"#{association}\", \"#{j(fields)}\")"
	end

end

app/views/comments/_comment.html.erb
<li><%= h(comment.content) %></li>

app/views/comments/create.js.erb
$('#comments').append("<%= render partial: 'comment', 
	                                locals: { comment: @comment } %>")

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Tester</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'nested_form','data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<h2><%= debug params %></h2><br \>
<!-- <p><%= debug session.to_hash %></p> -->
<%= yield %>

</body>
</html>

app/views/weddings/_form.html.erb
<%= form_for @wedding, html: { class: 'form-horizontal' } do |wedding_form| -%>
  <div class='form-group'>
    <%= wedding_form.label :title, class: 'col-sm-2 control-label' -%>
    <div class="col-sm-4">
      <%= wedding_form.text_field :title, class: 'form-control' -%>
    </div>
    <div class='col-sm-offset-1 col-sm-2'>
      <%= wedding_form.submit 'Save it', class: 'btn btn-primary' -%>
    </div>
  </div>
  <hr>
  <div class='gifts'>
    <%= wedding_form.fields_for :gifts do |gift_fields| -%>
      <%= render 'gift', gift_fields: gift_fields -%>
    <% end %>
  </div>
  <hr>
  <div class='form-group'>
    <%= link_to_add_fields 'Add Gift', wedding_form, :gifts -%>
  </div> 
<% end %>

app/views/weddings/_gift.html.erb
<div class="form-group">
  <%= gift_fields.label "Gifts", class: "col-sm-2 control-label" %>
  <div class="col-sm-4">
	<%= gift_fields.text_field :name, class: "form-control" %>
  </div>
  <div class="col-sm-offset-1 col-sm-2">
	<%= link_to "Delete", '#' , class: "delete-gift", onclick: "delete_gifts(this)" %>
	<%= gift_fields.hidden_field :id unless gift_fields.object.new_record? %>
	<%= gift_fields.hidden_field :_destroy , class: "destroy-mark" %>
  </div>
</div>

app/views/weddings/_wedding.html.erb
<tr>
  <td><%= link_to wedding.id, wedding_path(wedding) %></td>
  <td><%= wedding.title %></td>
  <td><%= wedding.url %></td>
  <td><%= wedding.gifts.count %></td>
  <td>
    <%= link_to t('.show', :default => t("helpers.links.show")),
                wedding_path(wedding), :class => 'btn btn-default btn-xs' %>
    <%= link_to t('.edit', :default => t("helpers.links.edit")),
                edit_wedding_path(wedding), :class => 'btn btn-default btn-xs' %>
    <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                wedding_path(wedding),
                :method => :delete,
                :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                :class => 'btn btn-xs btn-danger' %>
  </td>
</tr>

app/views/weddings/edit.html.erb
<%= render :partial => 'form' -%>

app/views/weddings/index.html.erb
<%- model_class = Wedding -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:title) %></th>
      <th><%= model_class.human_attribute_name(:url) %></th>
      <th><%= model_class.human_attribute_name(:Quantity) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
     <%= render partial: 'wedding', collection: @weddings %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_wedding_path,
            :class => 'btn btn-primary' %>

app/views/weddings/new.html.erb
<%= render 'form' %>

app/views/weddings/show.html.erb
<% cache @wedding do %>
  <p class='col-sm-offset-1'>Title : <%= @wedding.title %></p>
  <hr>
  <ul class='col-sm-offset-1'>
  <% @wedding.gifts.each do |g| %>
     <li><%= g.name %></li>
  <% end %>
  </ul>
  <hr>
  <ul id='comments' class='col-sm-offset-1'>
  <% @wedding.comments.each do |c| %>
     <%= render partial: c, locals: { comment: c }  %>
  <% end %>
  </ul>
  <hr>
<% end %>
<%= form_for Comment.new(wedding: @wedding), 
             remote: true,
             html: { class: 'form-horizontal' } do |f| %>
  <div class='form-group'>
    <div class='col-sm-offset-1 col-sm-4'>
      <%= f.hidden_field :wedding_id %>
      <%= f.text_field :content, class: 'form-control' %>
    </div>
  </div>
  <div class='form-group'>
    <div class='col-sm-offset-4 col-sm-2'>
      <%= f.submit 'Comment it', class: 'btn btn-primary' %>
    </div>
  </div>
    
<% end %>